#!/usr/bin/env python
import BaseHTTPServer
import SocketServer
from subprocess import check_output, CalledProcessError
from ConfigParser import ConfigParser, NoOptionError
import zlib

config = ConfigParser()
config.read('/etc/exec-exporter.ini')

class Handler(BaseHTTPServer.BaseHTTPRequestHandler):
	def do_GET(s):
		try:
			output = check_output(config.get('paths', s.path), shell=True)
		except NoOptionError:
			s.send_response(404)
			s.send_header('Content-type', 'text/plain')
			s.end_headers()
			s.wfile.write('404 Not Found.')
			return
		except CalledProcessError:
			s.send_response(502) # very bad gateway
			s.send_header('Content-type', 'text/plain')
			s.end_headers()
			return

		s.send_response(200)
		s.send_header('Content-type', 'text/plain')
		# XXX: sure not all clients can accept gzipped data, but in practice virtually no one will tell the difference
		s.send_header('Content-encoding', 'gzip')
		s.end_headers()

		z = zlib.compressobj(9, zlib.DEFLATED, zlib.MAX_WBITS | 16)
		s.wfile.write(z.compress(output) + z.flush())

if __name__ == '__main__':
	BaseHTTPServer.HTTPServer(('', 9999), Handler).serve_forever()
